#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/01283ea4-f4ca-4826-b931-8a833dfccaa5 # 
version: v1
title: Employee Management System
   
resourceTypes: !include resourceType.raml
traits: !include trait.raml
securitySchemes: 
  oauth_2_0: !include securityScheme.raml
types: 
  employee: !include schemas.raml
  
/employees:
  type: 
    collection: 
      exampleBody: !include employee.sample
  get:
    is: [
         searchable: {description: "with searchable fields: deptName", example: "['deptName','HR', 'equals']"},  
          orderable: {fieldsList: "salary"},
          pageable
        ]
    
  post: