#%RAML 1.0 NamedExample
value:

  -
    employeeId: 1
    employeeName: Pankaj
    deptName: Technology
    salary: 10000

  -
    employeeId: 2
    employeeName: KC
    deptName: HR
    salary: 10000
