#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/01283ea4-f4ca-4826-b931-8a833dfccaa5 # 
version: v1
title: Employee Management System
   
resourceTypes: !include resourceType.raml
traits: !include trait.raml
securitySchemes: 
  oauth_2_0: !include securityScheme.raml
types: 
  employee: !include schemas.raml
  
/employees:
  type: 
    collection: 
      exampleBody: !include employee.sample
  get:
    is: [
          orderable: {fieldsList: "salary"},
          pageable
        ]
    queryParameters: 
      deptName:
        required: false
        description: Employees who are working with this department
        enum: [HR,Technology,OS,ADMIN]
      salary:
        required: false
        description: employee searchable with this salary
  post:

  /{Id}:  
    type: 
      collecton-item: 
        examplePutBody: !include employeePut.sample
    get:   
    put:    
    delete:
      
    