
  collection: 
    description: Collection of available <<resourcePathName>> in EMS
    get:
      description: Get a list of all the <<resourcePathName>>
      responses: 
        200:
          body: 
            application/json:
              example: |
                [
                                  {
                                    "employeeId": 1,
                                    "employeeName": "Pankaj",
                                    "deptName": "Technology",
                                    "salary": 10000
                                  },
                                  {
                                    "employeeId": 2,
                                    "employeeName": "KC",
                                    "deptName": "HR",
                                    "salary": 5000
                                  }
                                ]

    post:
      description: |
        create an <<resourcePathName|!singularize>> record into EMS.
      body: 
        application/json:
          example: |
              <<exampleBody>>
      responses: 
        201:
          body: 
            application/json:
              example: |
                { "message": "The <<resourcePathName|!singularize>> has been properly entered" }             
  collecton-item:
    description: Entity representing a <<resourcePathName|!singularize>>
    get:
      description: 
        Get the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id |
         {<<resourcePathName|!singularize>>Id}
      responses: 
        200:
          body: 
            application/json: 
              example: |
                {
                      "employeeId": 1,
                      "employeeName": "Pankaj",
                      "deptName": "Technology",
                      "salary": 10000
                }
    put:
      description: 
        Update the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id |
          {<<resourcePathName|!singularize>>Id}
      body: 
        application/json:
          example: |
              <<examplePutBody>>
      responses: 
        200:
          body: 
            application/json:
              example: |
                { "message": "The <<resourcePathName|!singularize>> has been updated." }             
    delete:
      description: 
        delete the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id |
          {<<resourcePathName|!singularize>>Id}
      responses: 
        200:
          body: 
            application/json:
              example: |
                { "message": "The <<resourcePathName|!singularize>> has been deleted." }             

